### PR TITLE
Preserve runtime error node IDs from Resolve

### LINKED ISSUE #1191: 6b5d14c3 breaks resolution of runtime error locations in macros
**Describe the bug**

We use the NodeID() value from runtime errors to be able to locate runtime errors in programs. The change in 6b5d14c3 (identified by git bisect) appears to have broken this for nodes that exist within the AST in macro expansions. After the change, errors are noted as existing at the site of the unexpanded macro, rather than at the site within the macro's body.

For example with the following program:
```
get(state.url).Body.decode_json().records.map(r,
	get(state.url+'/'+r.id).Body.decode_json()).as(events, {
//                    ^~~~ r.id not converted to string: can't add integer to string.
		"events": events,
})
```
note that in this context, `state.url` is a `dyn` that is not known until runtime.

(before):
```
failed eval: ERROR: <input>:3:26: no such overload
 |   get(state.url+'/'+r.id).Body.decode_json()).as(events, {
 | .........................^
```
(after):
```
failed eval: ERROR: <input>:5:14: no such overload
 |    "events": events,
 | .............^
```

Neither is perfect, but the one after the change is worse.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Test setup:

Best done by reference to github.com/elastic/mito@48813c5bbc46326feb15c8aab98cb08bae2c1fa6 and the corresponding test adjustment in github.com/elastic/mito@6bd3ded032c5cd2bb44ca0aad50a14a80e736857

I can put together a smaller reproducer, but I'd like to get an idea of whether this is something that we just have to live with before I do that>

**Expected behavior**

Something more similar to the "before" case.

### PR DESCRIPTION
**Pull request by efd6**
# Pull Requests Guidelines

See [CONTRIBUTING.md](./CONTRIBUTING.md) for more details about when to create
a GitHub [Pull Request][1] and when other kinds of contributions or
consultation might be more desirable.

When creating a new pull request, please fork the repo and work within a
development branch.

## Commit Messages

* Most changes should be accompanied by tests.
* Commit messages should explain _why_ the changes were made.
```
Preserve runtime error node IDs from Resolve

When absoluteAttribute.Resolve() encounters a *types.Err variable value,
return it directly rather than calling Unwrap(). The Unwrap call strips
the Err wrapper and its node ID, causing callers to re-label the error
with the observation site's ID instead of the originating expression's ID.

Additionally, make WrapErr pass through existing *types.Err values rather
than double-wrapping them. This ensures that LabelErrNode sees the
original non-zero node ID and preserves it, regardless of the call site.

Fixes #1191
```

## Reviews

* Perform a self-review.
* Make sure the Travis CI build passes.
* Assign a reviewer once both the above have been completed.

## Merging

* If a CEL maintaner approves the change, it may be merged by the author if
  they have write access. Otherwise, the change will be merged by a maintainer.
* Multiple commits should be squashed before merging.
* Please append the line `closes #<issue-num>: description` in the merge message,
  if applicable.

[1]:  https://help.github.com/articles/about-pull-requests

### CODE REVIEW

File: interpreter/interpretable.go [hunk 1]
```diff
@@ -167,6 +167,9 @@ func (test *evalTestOnly) Eval(ctx Activation) ref.Val {
 	val, err := test.Resolve(ctx)
 	// Return an error if the resolve step fails
 	if err != nil {
+		if celErr, ok := err.(*types.Err); ok {
```
Comment (TristonianJones) [inline interpreter/interpretable.go]: Can you wrap the conditional check into the `types.WrapErr` directly? That will cover more branches of execution.

File: interpreter/attributes.go [hunk 2]
```diff
@@ -349,7 +349,7 @@ func (a *absoluteAttribute) Resolve(vars Activation) (any, error) {
 		obj, found := v.ResolveName(nm)
 		if found {
 			if celErr, ok := obj.(*types.Err); ok {
-				return nil, celErr.Unwrap()
+				return nil, celErr
```
Comment (TristonianJones) [inline interpreter/attributes.go:352]: Can you add the following repro case into `attributes_test.go` L1106:


```go
               {
                       expr: `['a', b.val, 'c'].filter(i, i + 'b' != 'ab')`,
                       vars: []*decls.VariableDecl{
                               decls.NewVariable("b", types.NewMapType(types.StringType, types.DynType)),
                       },
                       in: partialActivation(
                               map[string]any{
                                       "b": map[string]any{
                                               "val": 1,
                                       },
                               },
                       ),
                       // Error node 9 corresponds to the `i + 'b'` expression
                       out: types.LabelErrNode(9, types.NoSuchOverloadErr()),
               },
```

You'll also have to update the test conditions to the following L1173:

```diff
                        } else if tc.out.Equal(out) != types.True {
                                t.Errorf("got %v, wanted %v", out, tc.out)
                        }
+                       if err, isErr := out.(*types.Err); isErr && err.NodeID() != 0 {
+                               wantErr := tc.out.(*types.Err)
+                               if err.NodeID() != wantErr.NodeID() {
+                                       t.Errorf("err.NodeID() got %d, wanted %d", err.NodeID(), wantErr.NodeID())
+                               }
+                       }
                        for id, val := range tc.state {

```

**Review by TristonianJones — CHANGES_REQUESTED** [review]

**Comment by efd6** [comment]
PTAL

**Review by TristonianJones — APPROVED** [review]

**Review by TristonianJones — APPROVED** [review]
