### PR TITLE
Provide an option to ensure time operations are in UTC by default

### LINKED ISSUE #468: getHours() uses timezone of timestamp not UTC
According to the [CEL spec](https://github.com/google/cel-spec/blob/master/doc/langdef.md) `getHours()` should "get hours from the date in UTC, 0-23", but instead it uses the timezone of the timestamp object.

How to reproduce:

```
timestamp('2011-08-18T19:03:37.010+01:00').getHours() == timestamp('2011-08-18T19:03:37.010+01:00').getHours('UTC')
```

### PR DESCRIPTION
**Pull request by TristonianJones**
Currently, unary member functions on `timestamp` values in cel-go will use whatever the timezone is of the input object. However, this is not what is specified in the spec and can result in differences in evaluation behavior depending on where the call takes place. This fixes an issue with spec-conformance and should be enabled by default in future releases. To opt-in or opt-out see the usage below.

Usage: `cel.NewEnv(cel.DefaultUTCTimeZone(true))`

Closes #468 by ensuring that all time operations are in UTC by default.

### CODE REVIEW

File: cel/library.go [hunk 1]
```diff
@@ -75,3 +82,239 @@ func (stdLibrary) ProgramOptions() []ProgramOption {
...
+	if err != nil {
+		return time.Time{}, err
+	}
+	min, err := strconv.Atoi(string(val[ind+1]))
+	if err != nil {
+		return time.Time{}, err
+	}
+	var offset int
+	if string(val[0]) == "-" {
+		offset = hr*60 - min
```
Comment (jcking) [inline cel/library.go:312]: Is this correct? Shouldn't both components be negative? -1:30 means -90 minutes, no?

Comment (TristonianJones) [reply cel/library.go:312]: I think you're right. This bug has been here for a long time since I just copied it over from the `timestamp.go` object directly. I'll add tests and fix both locations.

Comment (TristonianJones) [reply cel/library.go:312]: Actually, I checked the math. This works out. The `hr` is already negative but `min` is positive, so `hr * 60 - min`  for a timezone of `-01:30` would result in an offset of `-1 * 60 - 30` or `-90` as you would expect.

Comment (TristonianJones) [reply cel/library.go:312]: Funnily enough, there was a different issue with the substring for the minutes offset, so the test caught a different issue. Thanks for asking me to double check here.

**Review by jcking — APPROVED** [review]
