### PR TITLE
The type map references when keyed by attribute may be incorrect.

### LINKED ISSUE #364: Attribute ids may result in sub-optimal proto field resolution
**Describe the bug**
The CEL `planner.go` periodically references the `checked.proto` reference map and type map to optimize the program plan. The keys to these maps are the expression identifiers related to the operation in question. When `Attribute` values were introduced, it was possible for the wrote id to be used with these maps and the optimizations to fail.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
proto.field1.field2
```

Test setup:
```go
	name:  "nested_proto_field",
	expr:  `pb3.single_nested_message.bb`,
	types: []proto.Message{&proto3pb.TestAllTypes{}},
	env: []*exprpb.Decl{
		decls.NewVar("pb3",
			decls.NewObjectType("google.expr.proto3.test.TestAllTypes")),
	},
	in: map[string]interface{}{
		"pb3": &proto3pb.TestAllTypes{
			NestedType: &proto3pb.TestAllTypes_SingleNestedMessage{
				SingleNestedMessage: &proto3pb.TestAllTypes_NestedMessage{
					Bb: 1234,
				},
			},
		},
	},
	out: types.Int(1234),
```

**Expected behavior**
The program evaluates the same way, but the expectation is that the field type of 'bb' would be found and extracted in a more optimal manner from its parent proto.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by TristonianJones**
Attribute ids refer to the first operand in the qualified field path; however, the type map and reference map ids refer to the last field in the qualified attribute field path. Ensure that the types and references are correctly determined by referring directly to the id as it comes from the `checked.proto` AST.

Closes #364

### CODE REVIEW

File: interpreter/interpreter_test.go [hunk 1]
```diff
@@ -515,6 +515,25 @@ var (
...
+				"pb3": &proto3pb.TestAllTypes{
+					NestedType: &proto3pb.TestAllTypes_SingleNestedMessage{
+						SingleNestedMessage: &proto3pb.TestAllTypes_NestedMessage{
+							Bb: 1234,
+						},
+					},
+				},
+			},
+			out: types.Int(1234),
+		},
```
Comment (JimLarson) [inline interpreter/interpreter_test.go:560]: So as I understand the comment, this test would pass without these changes. Could you have a test that fails without the changes? Also for an expression that uses indexing.

**Review by JimLarson — CHANGES_REQUESTED** [review]

File: interpreter/interpreter_test.go (hunk 1 above)
Comment (TristonianJones) [reply interpreter/interpreter_test.go:560]: The code is remarkably robust in that I only noticed the issue when looking at alloc counts from benchmarks. I'll see if I can add a test, but I think the nice thing about the current arrangement is that almost no matter what I do, the code will work. :)

**Comment by TristonianJones** [comment]
PTAL, I was able to add a test which checks for the specialized qualifier type `fieldQualifier` which can only appear when the optimization paths are built correctly.

**Review by JimLarson — APPROVED** [review]
Great, thanks!
