### PR TITLE
Fix shared state in Env extension

### LINKED ISSUE #333: Env.Extend() result shares state
**Describe the bug**
This is a minor issue that prevents using a shared parent Env to build multiple child Envs.

Env.Extend() returns a new Env that shares the underlying slices of the original Env. If I extend the same Env more than once then previous extended Envs can be modified by the current one. This is because they append into the same slice.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [ ]  interpreter

Test setup:
```go
func TestEnvExtends(t *testing.T) {
	baseEnv, err := cel.NewEnv(cel.Declarations(
		decls.NewIdent("age", decls.Int, nil),
		decls.NewIdent("gender", decls.String, nil),
		decls.NewIdent("country", decls.String, nil)))
	if err != nil {
		t.Fatal(err)
	}

	env1, err := baseEnv.Extend(cel.Declarations(
		decls.NewIdent("name", decls.String, nil)))
	if err != nil {
		t.Fatal(err)
	}

	env2, err := baseEnv.Extend(cel.Declarations(
		decls.NewIdent("group", decls.String, nil)))
	if err != nil {
		t.Fatal(err)
	}

	if _, issues := env2.Compile("size(group) > 10"); issues.Err() != nil {
		t.Fatal(issues.Err())
	}

	// I expect this to work but env1 now has "group" instead of "name"
	if _, issues := env1.Compile("size(name) > 10"); issues.Err() != nil {
		t.Fatal(issues.Err())
	}
}
```
```
--- FAIL: TestEnvExtends (0.01s)
    cel_test.go:37: ERROR: <input>:1:6: undeclared reference to 'name' (in container '')
         | size(name) > 10
         | .....^
```

**Expected behavior**
In the test case I expect env1 to have the declarations of baseEnv + name and env2 to have the declarations of baseEnv + group.

I'd also expect similar behavior for other configurable slice fields.

**Additional context**
I'm reporting this as an Env.Extend() issue but it could also be solved if the EnvOptions made new copies of slices instead of appending.

### PR DESCRIPTION
**Pull request by TristonianJones**
Ensure that slices with the `Env` object are deep-copied during the `Env.Extend` call to ensure extensions are isolated from each other.

Closes #333

### CODE REVIEW

**Comment by TristonianJones** [comment]
Thanks @mctofu for the detailed test case, that made the fix a snap to put together.

File: cel/cel_test.go [hunk 1]
```diff
@@ -709,6 +709,33 @@ func Test_EnvExtension(t *testing.T) {
...
+	}
+	env2, err := baseEnv.Extend(Declarations(
+		decls.NewIdent("group", decls.String, nil)))
+	if err != nil {
+		t.Fatal(err)
+	}
+	if _, issues := env2.Compile("size(group) > 10"); issues.Err() != nil {
+		t.Fatal(issues.Err())
+	}
+	// I expect this to work but env1 now has "group" instead of "name"
```
Comment (JimLarson) [inline cel/cel_test.go]: Remove this comment now that you've fixed the bug.

File: cel/cel_test.go [hunk 2]
```diff
@@ -709,6 +709,33 @@ func Test_EnvExtension(t *testing.T) {
...
+	if _, issues := env1.Compile("size(name) > 10"); issues.Err() != nil {
+		t.Fatal(issues.Err())
+	}
```
Comment (JimLarson) [inline cel/cel_test.go:772]: Also test that `env1` does not declare `group` and `env2` does not declare `name`.

File: cel/env.go [hunk 3]
```diff
@@ -209,13 +209,20 @@ func (e *Env) Extend(opts ...EnvOption) (*Env, error) {
...
+	copy(decsCopy, e.declarations)
+	copy(macsCopy, e.macros)
+	copy(progOptsCopy, e.progOpts)
+
 	ext := &Env{
-		declarations:                   e.declarations,
+		declarations:                   decsCopy,
+		macros:                         macsCopy,
+		progOpts:                       progOptsCopy,
 		adapter:                        e.adapter,
```
Comment (JimLarson) [inline cel/env.go]: Check that the adapter isn't mutable.

**Review by JimLarson — CHANGES_REQUESTED** [review]

File: cel/cel_test.go (hunk 2 above)
Comment (TristonianJones) [reply cel/cel_test.go:772]: Done.

File: cel/cel_test.go (hunk 1 above)
Comment (TristonianJones) [reply cel/cel_test.go]: Done.

File: cel/env.go (hunk 3 above)
Comment (TristonianJones) [reply cel/env.go]: It's an interface, so its mutability depends on the implementation. Our `ref.TypeRegistry` is inherently mutable, so I've added `Copy` methods to the `ref.TypeRegistry` as well as to the `pb.Db` to make it easier to ensure isolated memory. Note, the `pb.Db` copy is a shallow copy since the `FileDescription` and related objects are intended to be singletons.

**Comment by TristonianJones** [comment]
PTAL

File: cel/env.go [hunk 4]
```diff
@@ -205,18 +205,52 @@ func (e *Env) CompileSource(src common.Source) (*Ast, *Issues) {
...
+	// TypeRegistry as the base implementation are captured below.
+	if isAdapterReg && isProviderReg && adapterReg == providerReg {
+		reg := providerReg.Copy()
+		adapter = reg
+		provider = reg
+	} else if isProviderReg {
+		provider = providerReg.Copy()
+	} else if isAdapterReg {
+		adapter = adapterReg.Copy()
+	}
```
Comment (JimLarson) [inline cel/env.go:244]: Looks like `adapter`, `provider`, or both can still be uninitialized/nil at this point.  Should they default to `e.adapter` and `e.provider`?  Or maybe the adapter and provider interfaces should include the Copy method?  (That would complicate the sharing.)

Comment (TristonianJones) [reply cel/env.go:244]: Oops, I'd started with using e.adapter and e.provider as defaults and accidentally undid it. That's what I'd intended at least. Will fix

Comment (TristonianJones) [reply cel/env.go:244]: Fixed and added a test case using an immutable adapter.

**Review by JimLarson — APPROVED** [review]

File: cel/env.go [hunk 5]
```diff
@@ -205,18 +205,52 @@ func (e *Env) CompileSource(src common.Source) (*Ast, *Issues) {
...
+	// In most cases the provider and adapter will be a ref.TypeRegistry;
+	// however, in the rare cases where they are not, they are assumed to
+	// be immutable. Since it is possible to set the TypeProvider separately
+	// from the TypeAdapter, the possible configurations which could use a
+	// TypeRegistry as the base implementation are captured below.
+	if isAdapterReg && isProviderReg && adapterReg == providerReg {
+		reg := providerReg.Copy()
+		adapter = reg
+		provider = reg
+	} else if isProviderReg {
```
Comment (mctofu) [inline cel/env.go:240]: if isAdapterReg && isProviderReg && adapterReg != providerReg should this be making a copy of both providerReg and adapterReg instead of just providerReg?

Comment (TristonianJones) [reply cel/env.go:240]: The test here is saying that the adapter and provider are the same `ref.TypeRegistry` so only one copy is needed and desired. 

Thanks for following up!

Comment (mctofu) [reply cel/env.go:240]: The case I was wondering about is if adapter and provider are both `ref.TypeRegistry` but different ones. I'm not sure if that's an expected case but it looks like we wouldn't copy both of them?

**Comment by TristonianJones** [comment]
Ah, I see. I'll amend the code. Thanks

File: cel/env.go (hunk 5 above)
Comment (TristonianJones) [reply cel/env.go:240]: Ah, yes. You're right. I have been bouncing between a few different roles here at home and missed that case. It's possible for this to happen, but should be incredibly uncommon. I'll amend the code.
