### PR TITLE
Validators for common literals and use cases

### LINKED ISSUE #359: Check the timestamp format at compile time
Correct me if I'm wrong, but the only way to know if the timestamp format is right, is to evaluate the expression?

Wouldn't be nice to know that before, at parse/check time?

e.g.

```go
func TestTimestamp(t *testing.T) {
	// create env
	env, err := cel.NewEnv(
		cel.Declarations(
			decls.NewVar("date", decls.Timestamp)))
	if err != nil {
		t.Error(err)
	}

	// compile (parse+check)
	_, issues := env.Compile(`date > timestamp('wrong timestamp')`)
	if issues != nil && issues.Err() != nil {
		t.Fatal("I want to err here!")
	}
}
```

We are using parse+check to generate an AST, using that AST as an input to a filter component, who generates SQL from it.

This would allow us to support timestamp without having to evalute the expression just for that, or introducing custom code to post-check the AST, if the format passed to `timestamp("wrong")` is wrong.

I suppose this could apply for duration as well.

### LINKED ISSUE #496: Type check and pre-compile fixed regex strings
**Change**

Currently regex patterns are compiled at runtime each time a matches() invocation is evaluated by the interpreter.

Instead, if the regex patterns is a string constant (e.g. `x.matches('[0-9]+')`)
- Check the regex at compile time and return a type check error if the regex string is malformed (similar in spirit to https://github.com/google/cel-go/issues/359)
- Pre-compile regex at CEL compile time (at least for programs where `OptOptimize` is enabled) and reuse it at runtime instead of recompiling it for each invocation

**Example***

`x.matches('[0-9]+') // regex pattern is fixed, so type check it and pre-compile it at CEL compile time

`x.matches(foo.pattern)` // regex pattern is from a variable input so continue to compile it at runtime for each matches() invocation

**Alternatives considered**

I'm open to ideas here.

Based on what little I know of CEL, the approach that came to mind is:
- Annotate Function Overloads to identify arguments that are regex pattern strings
- Modify the type checker to look for regex pattern arguments where the arg expression is a const, compile the regex and report any errors
- Modify the planner to drop in a new type of Interpretable for regex pattern argument exprs that holds the compiled regex. Also add a new ref.Val type that the new Interpretable can return that holds a reference to the compile regex in addition to the string constant the ref.Val represents.  matches() can then inspect the ref.Val to see if it has a pre-compiled regex, and use if it is does (otherwise it can compile as usual)

### LINKED ISSUE #655: string.format() cannot be used as intended with HomogeneousAggregateLiterals
We encountered this with Kubernetes, where we have `HomogeneousAggregateLiterals` enabled.

`string.format()` takes a list of values to interpolate in a formatted string, e.g. `"%s - %d".format(['a', 1])`.

When `HomogeneousAggregateLiterals` is enabled, CEL enforces that the items of a literal list be the same type.

The result is that expressions like `"%s - %d".format(['a', 1])` are not allowed when `HomogeneousAggregateLiterals` is enabled.

### PR DESCRIPTION
**Pull request by TristonianJones**
Introduce validators for duration, timestamp, and regex string literals as well as support for homogeneous aggregate literals with a carve-out for string format calls.

Closes #359 
Closes #496 
Closes #655

### CODE REVIEW

**Review by TristonianJones — COMMENTED** [review]
@DangerOnTheRanger @jpbetz @cici37 What do you think of the validator support being added here? I 'll update the string formatting checks to happen immediately after type-check in a subsequent PR, but I wanted to showcase what could be done with the latest improvements.  I'm also tempted to update the checker cost model to use the new NavigableExpr type since it's more thorough than the decorators and easier to manage. Thoughts?

This PR will be introduced after #762 is reviewed and submitted.

File: cel/env.go [hunk 1]
```diff
@@ -207,12 +209,22 @@ func (e *Env) Check(ast *Ast) (*Ast, *Issues) {
...
-	return &Ast{
+	ast = &Ast{
 		source:  ast.Source(),
 		expr:    res.Expr,
 		info:    res.SourceInfo,
 		refMap:  res.ReferenceMap,
-		typeMap: res.TypeMap}, nil
+		typeMap: res.TypeMap}
+
+	// Apply additional validators on the type-checked result.
```
Comment (l46kok) [inline cel/env.go:223]: Could we also update the method documentation around this change?

File: cel/validator.go [hunk 2]
```diff
@@ -0,0 +1,282 @@
...
+// ValidateRegexLiterals ensures that regex patterns are validated after type-check.
+func ValidateRegexLiterals() ASTValidator {
+	return newFormatValidator(overloads.Matches, 0, compileRegex)
+}
+
+// ValidateHomogeneousAggregateLiterals checks that all list and map literals entries have the same types, i.e.
+// no mixed list element types or mixed map key or map value types.
+//
+// Note: the string format call relies on a mixed element type list for ease of use, so this check skips all
+// literals which occure within string format calls.
```
Comment (l46kok) [inline cel/validator.go]: nit: 

```suggestion
// literals which occur within string format calls.
```

File: cel/validator.go [hunk 3]
```diff
@@ -0,0 +1,282 @@
...
+
+type formatValidator struct {
+	funcName string
+	argNum   int
+	check    argChecker
+}
+
+// Name returns the unique name of this function format validator.
+func (v formatValidator) Name() string {
+	return fmt.Sprintf("cel.lib.std.functions.%s", v.funcName)
```
Comment (l46kok) [inline cel/validator.go]: Thoughts on including "validator" somewhere in the name? `cel.lib.std.functions.timestamp` for example sounds like a generic standard function.

File: cel/validator.go [hunk 4]
```diff
@@ -0,0 +1,282 @@
...
+				v.typeMismatch(errs, key.ID(), keyType, kt)
+			}
+			if !valType.IsEquivalentType(vt) {
+				v.typeMismatch(errs, val.ID(), valType, vt)
+			}
+		}
+	}
+}
+
+func hasStringFormatAncestor(e ast.NavigableExpr) bool {
```
Comment (l46kok) [inline cel/validator.go:224]: I'm a bit torn on this. IMO, I think this type of check is too specific for homogeneous literal validation to be concerned of, especially considering that `string.format` is not part of the standard library. I think I would've preferred an approach where the string formatter validator composes homogenous literal validator then decide how to validate.

File: cel/validator.go [hunk 5]
```diff
@@ -0,0 +1,282 @@
...
+type errorReporter struct {
+	iss  *Issues
+	info *exprpb.SourceInfo
+}
+
+func (er *errorReporter) reportErrorAtID(id int64, message string, args ...any) {
+	er.iss.errs.ReportErrorAtID(id, locationByID(id, er.info), message, args...)
+}
+
+func locationByID(id int64, sourceInfo *exprpb.SourceInfo) common.Location {
```
Comment (l46kok) [inline cel/validator.go:260]: Some of the functions here, such as this seems useful enough to offer in a common helper.

Comment (TristonianJones) [reply cel/validator.go:260]: I ended up moving most of this functionality up into the `Issues` object in a later PR. See https://github.com/google/cel-go/pull/768 cel/env.go line 693. I can probably move that change into its own PR if you want.

File: cel/validator.go (hunk 4 above)
Comment (TristonianJones) [reply cel/validator.go:224]: Since I don't know when the validators will be applied (or if they're applied), I think I have to have a carve-out here for format checking. I can make it more dynamic in the sense that it can check for library enablement to determine what to do, but I'm not sure I can do much better than that. 

If you switch the order of `ext.Strings()` and `cel.HomogeneousAggregateLiterals()` in the `NewEnv()` call, I think there's a risk that the format validator might not see the aggregate literal validator or vice-versa. The only other thing I can do is allow for replacement of the validator, but that's a bit risky since the order in which the validators are added would influence the outcome.

File: cel/validator.go (hunk 3 above)
Comment (TristonianJones) [reply cel/validator.go]: SGTM.

File: cel/validator.go (hunk 4 above)
Comment (TristonianJones) [reply cel/validator.go:224]: I'm okay with adding a TODO and coming back to this on a subsequent PR. I thought maybe I could make the check generic in the sense that if the specific overload expects a `list(dyn)` element type (I believe format is one of the few, possibly only), then homogeneous aggregate literal checks could be disabled since that was the developer's intent, but I'm not sure how string.format does it will be how other functions expect it to work.

File: cel/env.go (hunk 1 above)
Comment (TristonianJones) [reply cel/env.go:223]: Done.

File: cel/validator.go (hunk 5 above)
Comment (l46kok) [reply cel/validator.go:260]: This is OK, we can bring in the change with the linked PR

**Review by l46kok — APPROVED** [review]
