### PR TITLE
Fix two-variable comprehension pruning

### LINKED ISSUE #1080: Two variable comprehensions potentially getting lost during pruning
**Describe the bug**

I am not quite sure whether this is a bug or not. I was reading the source to track down a different problem and came across this, which seems odd to me.

https://github.com/google/cel-go/blob/5d18e93d204801cbe02158a0ddb3a3abce29e4ed/interpreter/prune.go#L418-L433

Shouldn't it check `compre.IterVar2` and return a `p.NewComprehensionTwoVar(...)` if it's not empty?

Similarly, shouldn't there be a check for a two variable comprehension in the following bit as well?

https://github.com/google/cel-go/blob/5d18e93d204801cbe02158a0ddb3a3abce29e4ed/interpreter/prune.go#L284-L287

### PR DESCRIPTION
**Pull request by TristonianJones**
Added support for two-variable comprehension prune / unparse

Closes #1080

### CODE REVIEW

File: ext/comprehensions_test.go [hunk 1]
```diff
@@ -345,6 +345,62 @@ func TestTwoVarComprehensionsRuntimeErrors(t *testing.T) {
 	}
 }
 
+func TestTwoVarComprehensionsUnparse(t *testing.T) {
```
Comment (jnthntatum) [inline ext/comprehensions_test.go:364]: could you update this test to include a PruneAST example that would have failed?

Comment (TristonianJones) [reply ext/comprehensions_test.go:348]: I think all of these tests would have failed since the second variable would have been omitted. Happy to add more cases if you have some in mind

Comment (TristonianJones) [reply ext/comprehensions_test.go:364]: Oh, of course, I should actually add tests for pruning. Sorry about that

Comment (TristonianJones) [reply ext/comprehensions_test.go:364]: PTAL, the change ended up being much more invasive than I had originally anticipated.

File: interpreter/prune.go [hunk 2]
```diff
@@ -281,13 +281,35 @@ func (p *astPruner) prune(node ast.Expr) (ast.Expr, bool) {
...
 		if node.Kind() == ast.ComprehensionKind {
 			compre := node.AsComprehension()
 			visit(macro, clearIterVarVisitor(compre.IterVar(), p.state))
+			if compre.HasIterVar2() {
+				visit(macro, clearIterVarVisitor(compre.IterVar2(), p.state))
+			}
+			loopCond := compre.LoopCondition()
+			iterRange := compre.IterRange()
+			pruneMacroCall =
+				(loopCond.Kind() == ast.LiteralKind && loopCond.AsLiteral() == types.False) &&
```
Comment (jnthntatum) [inline interpreter/prune.go]: nit/clarity -- could you add a comment or add a predicate function for this test (checking for trivial comprehension)? does this also apply to .optMap?

**Review by jnthntatum — CHANGES_REQUESTED** [review]

File: interpreter/prune.go (hunk 2 above)
Comment (TristonianJones) [reply interpreter/prune.go]: Perhaps I should just restrict the pruning to `cel.bind` calls only since `optMap` although not wrong would look very strange. Thoughts?

Comment (jnthntatum) [reply interpreter/prune.go]: Just testing for cel.bind is easier to follow imo, but up to you.

**Review by jnthntatum — DISMISSED** [review]

File: interpreter/prune.go (hunk 2 above)
Comment (TristonianJones) [reply interpreter/prune.go]: Done, PTAL.

**Review by jnthntatum — APPROVED** [review]
