### PR TITLE
Check time support for JSON and well-known types.

### LINKED ISSUE #47: JSON and well-known types not handled properly during type-resolution
## Issue Filing Checklist

- [X] There are no issues that match the desired change
- [X] The change is large enough it can't be addressed with a simple [Pull Request](./PULL_REQUEST_TEMPLATE.md) 
- [X] If this is a bug, there are a concrete set of repro steps

## Change
When a value has a `google.protobuf.Value` type (or derivative), or a well-known type
such as `google.protobuf.Any` or `google.protobuf.Duration`, the type is treated as a
`MESSAGE` by the `checker.go` when it should be mapped to the appropriate built-in
or well-known type value.

### PR DESCRIPTION
**Pull request by TristonianJones**
Built-in CEL types based on protobufs were not properly being identified at `check` time when
referenced by their proto message name. This change sanitizes the environment by mapping
proto messages to their appropriate CEL built-in type when appropriate. 

closes #47

### CODE REVIEW

File: checker/env.go [hunk 1]
```diff
@@ -142,57 +186,104 @@ func (e *Env) addIdent(decl *exprpb.Decl) errorMsg {
...
+		// If sanitized, replace the overload definition.
+		if sanitized {
+			if o.IsInstanceFunction {
+				overloads[i] =
+					decls.NewInstanceOverload(o.GetOverloadId(), params, rt)
+			} else {
+				overloads[i] =
+					decls.NewOverload(o.GetOverloadId(), params, rt)
+			}
+			// Otherwise, preserve the original overload.
```
Comment (JimLarson) [inline checker/env.go]: Move this comment down after the "else".

**Review by JimLarson — APPROVED** [review]
