### PR TITLE
Fixed numeric offset timezones

### LINKED ISSUE #191: Support numeric offset timezones
**Describe the bug**
The spec describes an option for timezones to be of the form (+|-)?dd:dd, but this implementation doesn't support them.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
timestamp('2009-02-13T23:31:30Z').getDayOfMonth('+11:00')
```

Should return 13.

**Expected behavior**
The timezone should be the hours/minutes offset from UTC.

### PR DESCRIPTION
**Pull request by victoriajyang**
Fixed numeric offset timezones and added new tests in buildfile.
Closes #191

### CODE REVIEW

File: common/types/timestamp.go [hunk 1]
```diff
@@ -272,12 +274,33 @@ func timestampGetMillisecondsWithTz(t time.Time, tz ref.Val) ref.Val {
 
 func timeZone(tz ref.Val, visitor timestampVisitor) timestampVisitor {
 	return func(t time.Time) ref.Val {
+		var err error
+		var offset int
```
Comment (JimLarson) [inline common/types/timestamp.go]: Don't declare these here.  See below for specifics.

File: common/types/timestamp.go [hunk 2]
```diff
@@ -272,12 +274,33 @@ func timestampGetMillisecondsWithTz(t time.Time, tz ref.Val) ref.Val {
...
 			return ValOrErr(tz, "no such overload")
 		}
-		loc, err := time.LoadLocation(string(tz.(String)))
-		if err == nil {
-			return visitor(t.In(loc))
+		val := string(tz.(String))
+		ind := strings.Index(val, ":")
+		if ind == -1 {
+			loc, err := time.LoadLocation(val)
+			if err == nil {
```
Comment (JimLarson) [inline common/types/timestamp.go]: Negate the test and put a "return &Err{err}" inside the "if", and have the happy path "return visitor..." after the "if".  Then, since all paths here end in a return, you can eliminate the "else" and outdent its code.

File: common/types/timestamp.go [hunk 3]
```diff
@@ -272,12 +274,33 @@ func timestampGetMillisecondsWithTz(t time.Time, tz ref.Val) ref.Val {
...
+				return visitor(t.In(loc))
+			}
+		} else {
+			hr, err := strconv.Atoi(string(val[0:ind]))
+			min, err2 := strconv.Atoi(string(val[ind+1]))
+			if err == nil && err2 == nil {
```
Comment (JimLarson) [inline common/types/timestamp.go]: Little bug here - if err == nil but err2 is non-nil, we'll end up returning an Err with an empty reason.

Instead, test err right after it's set and split out the error case, then instead of err2, just reuse err for the "min" parsing and also check for errors there.

File: common/types/timestamp.go [hunk 4]
```diff
@@ -272,12 +274,33 @@ func timestampGetMillisecondsWithTz(t time.Time, tz ref.Val) ref.Val {
...
-		if err == nil {
-			return visitor(t.In(loc))
+		val := string(tz.(String))
+		ind := strings.Index(val, ":")
+		if ind == -1 {
+			loc, err := time.LoadLocation(val)
+			if err == nil {
+				return visitor(t.In(loc))
+			}
+		} else {
```
Comment (JimLarson) [inline common/types/timestamp.go:304]: Start with a comment describing what you're parsing here.

File: common/types/timestamp.go [hunk 5]
```diff
@@ -272,12 +274,33 @@ func timestampGetMillisecondsWithTz(t time.Time, tz ref.Val) ref.Val {
...
+			hr, err := strconv.Atoi(string(val[0:ind]))
+			min, err2 := strconv.Atoi(string(val[ind+1]))
+			if err == nil && err2 == nil {
+				if string(val[0]) == "-" {
+					offset = hr*60 - min
+				} else {
+					offset = hr*60 + min
+				}
+				secondsEastOfUTC := int((time.Duration(offset) * time.Minute).Seconds())
+				timezone := time.FixedZone("Time Zone", secondsEastOfUTC)
```
Comment (JimLarson) [inline common/types/timestamp.go]: We don't have a meaningful name here, so just use an empty string.

File: common/types/timestamp.go [hunk 6]
```diff
@@ -272,12 +274,33 @@ func timestampGetMillisecondsWithTz(t time.Time, tz ref.Val) ref.Val {
...
+				curr_time := time.Date(t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), timezone)
```
Comment (JimLarson) [inline common/types/timestamp.go]: The timezone is a valid location - any reason not to just use visitor(t.In(timezone))?

**Review by JimLarson — CHANGES_REQUESTED** [review]

**Review by JimLarson — APPROVED** [review]
