### PR TITLE
Clear iteration variable data during expression pruning

### LINKED ISSUE #735: interpreter.PruneAst does not prune `IterRange` expression
**Describe the bug**
interpreter.PruneAst function ignores the `IterRange` field of a comprehension expression.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:

`users` is a list of const strings, and `R` is an unknown attribute pattern.

```cel
users.filter(u, u.startsWith(R.attr.prefix))
```

Test setup:
```go
package main

import (
	"fmt"
	"log"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/checker/decls"
	"github.com/google/cel-go/interpreter"
	expr "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
)

func main() {
	env, err := cel.NewEnv(cel.Declarations(
		decls.NewVar("R", decls.NewMapType(decls.String, decls.Dyn)),
		decls.NewVar("users", decls.NewListType(decls.String)),
	))
	exitOnErr(err)

	ast, iss := env.Compile(`users.filter(u, u.startsWith(R.attr.prefix))`)
	exitOnErr(iss.Err())

	prg, err := env.Program(ast, cel.EvalOptions(cel.OptTrackState, cel.OptPartialEval))
	exitOnErr(err)

	in := map[string]any{
		"users": []string{"alice", "bob"},
	}
	vars, err := cel.PartialVars(in, cel.AttributePattern("R").QualString("attr").Wildcard())
	exitOnErr(err)

	_, details, err := prg.Eval(vars)
	exitOnErr(err)

	pruned := interpreter.PruneAst(ast.Expr(), ast.SourceInfo().GetMacroCalls(), details.State()).Expr
	ce := pruned.ExprKind.(*expr.Expr_ComprehensionExpr).ComprehensionExpr
	printExpr("IterRange:", ce.IterRange)
}

func printExpr(name string, e *expr.Expr) {
	prunedAST := cel.ParsedExprToAst(&expr.ParsedExpr{Expr: e})
	s, err := cel.AstToString(prunedAST)
	exitOnErr(err)
	fmt.Println(name, s)
}

func exitOnErr(err error) {
	if err != nil {
		log.Fatalf("Error: %v", err)
	}
}

```

**Expected behavior**
The output should be:

```
IterRange: ["alice", "bob"]
```

instead of
```
IterRange: users
```

**Additional context**
This works as expected in v0.15.2, but in v0.15.3, the pruner [was modified](https://github.com/google/cel-go/pull/705/files#diff-531f45e46499da01fa105d485bd3d5765123ee5624c4128cad21545ce18bce25L411-L431) to skip the `IterRange` expression. Is this a breaking change?

### PR DESCRIPTION
**Pull request by TristonianJones**
This PR clears iteration variable data from expression tracking state during macro pruning.
The clearing of the iteration variable is based on the iteration variable name which could
potentially shadow an existing, but in the worst case, this would just cause a duplicate name
to be cleared more than once in a nested macro scope.

Closes #735

### CODE REVIEW

File: interpreter/prune.go [hunk 1]
```diff
@@ -341,6 +341,12 @@ func (p *astPruner) prune(node *exprpb.Expr) (*exprpb.Expr, bool) {
 		}
 	}
 	if macro, found := p.macroCalls[node.GetId()]; found {
+		// Ensure that intermediate values for the comprehension are cleared during pruning
+		compre := node.GetComprehensionExpr()
+		if compre != nil {
+			visit(macro, clearIterVarVisitor(compre.IterVar, p.state))
+			visit(macro, clearIterVarVisitor(compre.AccuVar, p.state))
```
Comment (l46kok) [inline interpreter/prune.go]: Does the accumulation variable actually need to be cleared here? If so, could we add a test for this

Comment (TristonianJones) [reply interpreter/prune.go]: Oh, no, you're right. We can skip the accumulation variable clearing since it never appears in the macro call AST

**Comment by TristonianJones** [comment]
PTAL

**Review by l46kok — APPROVED** [review]
