### PR TITLE
Fix for planner panic.

### LINKED ISSUE #245: Planner doesn't pass TypeProvider to evalIdent
**Describe the bug**
planner.go doesn't pass the type provider to `evalIdent` https://github.com/google/cel-go/blob/v0.2.0/interpreter/planner.go#L195 causing a panic in https://github.com/google/cel-go/blob/v0.2.0/interpreter/planner.go#L621 when using a custom type provider and `NewInterpretable` instead of `NewUncheckedInterpretable`

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
Can invest time in extracting a reproducible code sample if this is considered an actual issue. 

**Expected behavior**
Provider is used to resolve the type instead of a panic.

### PR DESCRIPTION
**Pull request by TristonianJones**
Fixed a missing `provider` value within the `evalIdent` on the checked expression paths.

Closes #245

### CODE REVIEW

File: interpreter/interpreter_test.go [hunk 1]
```diff
@@ -828,6 +828,30 @@ func TestInterpreter_SetProto2PrimitiveFields(t *testing.T) {
...
+	if len(errors.GetErrors()) != 0 {
+		t.Fatalf(errors.ToDisplayString())
+	}
+
+	interp := NewStandardInterpreter(packages.NewPackage("test"), reg, reg)
+	i, _ := interp.NewInterpretable(checked)
+	vars := EmptyActivation()
+	result := i.Eval(vars)
+	if !types.IsUnknownOrError(result) {
+		t.Errorf("Got %v, wanted unknown", result)
```
Comment (JimLarson) [inline interpreter/interpreter_test.go:852]: We actually want an error, right?

**Review by JimLarson — CHANGES_REQUESTED** [review]

**Comment by TristonianJones** [comment]
The current behavior will be unknown, but in the future it'll be an error.
I'll change the test name to reflect the issue being exercised

File: interpreter/interpreter_test.go [hunk 2]
```diff
@@ -847,7 +847,7 @@ func TestInterpreter_CustomTypeProvider(t *testing.T) {
 	i, _ := interp.NewInterpretable(checked)
 	vars := EmptyActivation()
 	result := i.Eval(vars)
-	if !types.IsUnknownOrError(result) {
+	if !types.IsUnknown(result) {
```
Comment (JimLarson) [inline interpreter/interpreter_test.go:851]: Since we want the result to be an error in the future, I was suggesting leaving the test as IsUnknownOrError but changing the message to "wanted error" or "wanted unknown or error".

**Review by JimLarson — CHANGES_REQUESTED** [review]

File: interpreter/interpreter_test.go (hunk 2 above)
Comment (TristonianJones) [reply interpreter/interpreter_test.go:851]: I've updated the test condition with a TODO since it reflects the current state of the code and will have to be updated in order to address Issue #190.

Comment (JimLarson) [reply interpreter/interpreter_test.go:851]: I would have been happy with the unknown-or-error check, with a note to clean up after the fix, but this is okay for now.

**Review by JimLarson — APPROVED** [review]
