### PR TITLE
Top-level support for partial state evaluation

### LINKED ISSUE #299: Ensure UnknownActivation is generated from the declared environment.
**Describe the bug**
Currently the `UnknownActivation` is a catchall object that always returns `types.UnknownSet`
when the variable name requested is not found. This causes issues where a type of the same
name as the 

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
// if an UnknownActivation is used, then `int` (as a variable) would return unknown;
// shadowing of identifier names should be supported, so this toy showcases a problem where
// the shadowing is not honored.
int 
```

**Expected behavior**
The use of an `UnknownActivation` should follow identifier shadowing rules.

**Additional context**

### PR DESCRIPTION
**Pull request by TristonianJones**
This PR introduces top-level support for evaluating partial state and computing residual CEL expressions. 

The following partial attribute evaluation features have been exposed in the `cel` package:

* `OptPartialEval` - Enable partial attribute evaluation for a specific program.
* `PartialVars` - Provide variables, and mark variables or data within a variable's object
     member graph as unknown
* `AttributePattern` - Helper method to create a new attribute pattern which can be used
    to match unknown state for an object or some part of an object.
*  `ResidualAst` - Compute a new parsed / checked `Ast` from an original `Ast` and the
   `EvalDetails` captured from a previous evaluation.

Attribute patterns start with a variable can have an optional set of qualifier patterns which
can be any valid map key type (`string`, `int64`, `uint64`, `bool`) or wildcard. The attribute
pattern behaves similarly to a [`protobuf.FieldMask`](https://godoc.org/google.golang.org/genproto/protobuf/field_mask), but with support for array element
indexing.

Note, computing a residual does not yet work for comprehension macros and depends on the addition of source info for macro replacements (#292).  

Closes #299

### CODE REVIEW

File: cel/env.go [hunk 1]
```diff
@@ -186,6 +187,62 @@ func (e *Env) TypeProvider() ref.TypeProvider {
...
+
+// ResidualAst takes an Ast and its EvalDetails to produce a new Ast which only contains the
+// attribute references which are unknown.
+//
+// Residual expressions are beneficial in a few scenarios:
+//
+// - Optimizing constant expression evaluations away.
+// - Indexing and pruning expressions based on known input arguments.
+// - Surfacing additional requirements that are needed in order to complete an evaluation.
+// - Sharing the evaluation of an expression across multiple processes
```
Comment (JimLarson) [inline cel/env.go]: Consider changing to "Sharing the evaluation of an expression across concurrent computations."  The expression could, for example, be evaluated across multiple threads in the same process.  Or if you want to highlight that it could be a distributed implementation, then "across multiple machines/nodes".

File: cel/env.go [hunk 2]
```diff
@@ -186,6 +187,62 @@ func (e *Env) TypeProvider() ref.TypeProvider {
...
+//
+// For example, if an expression targets a 'resource' and 'request' attribute and the possible
+// values for the resource are known, a PartialActivation could mark the 'request' as an unknown
+// interpreter.AttributePattern and the resulting ResidualAst would be reduced to only the parts
+// of the expression that reference the 'request'.
+//
+// See the PartialVars helper for how to construct a PartialActivation.
```
Comment (JimLarson) [inline cel/env.go:228]: Add a note that the expression IDs of the residual AST have no correlation to the expression IDs of the original AST.

File: cel/cel_test.go [hunk 3]
```diff
@@ -600,6 +599,90 @@ func Test_EvalRecover(t *testing.T) {
...
+	}
+	residual, err := e.ResidualAst(ast, det)
+	if err != nil {
+		t.Fatal(err)
+	}
+	expr, err := AstToString(residual)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if expr != "x < 10" {
```
Comment (JimLarson) [inline cel/cel_test.go:629]: I'm a little worried that we're setting precedent that the results of AstToString are stable to the level of whitespace.

File: cel/program.go [hunk 4]
```diff
@@ -48,6 +48,37 @@ func NoVars() interpreter.Activation {
 	return interpreter.EmptyActivation()
 }
 
+// PartialVars returns a PartialActivation which contains variables and a set of AttributePattern
+// values that indicate variables or parts of variables whose value are not yet known.
```
Comment (JimLarson) [inline cel/program.go:52]: As always, indicate what sorts of things "vars" could be.

File: cel/cel_test.go [hunk 5]
```diff
@@ -600,6 +599,90 @@ func Test_EvalRecover(t *testing.T) {
...
+	residual, err := e.ResidualAst(ast, det)
+	if err != nil {
+		t.Fatal(err)
+	}
+	expr, err := AstToString(residual)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if expr != `request.auth.claims.email == "wiley@acme.co"` {
+		t.Errorf("Got expr: %s, wanted x < 10", expr)
```
Comment (JimLarson) [inline cel/cel_test.go]: wanted request.auth.claims.email == "wiley@acme.co"

File: cel/program.go [hunk 6]
```diff
@@ -48,6 +48,37 @@ func NoVars() interpreter.Activation {
...
+	unknowns ...*interpreter.AttributePattern) (interpreter.PartialActivation, error) {
+	return interpreter.NewPartialActivation(vars, unknowns...)
+}
+
+// AttributePattern represents a top-level variable with an optional set of qualifier patterns.
+//
+// The variable name must always be a string, and may be a qualified name according to the CEL
+// namespacing conventions, e.g. 'ns.app.a'.
+//
+// The qualifier patterns for attribute matching must be one of the following:
```
Comment (JimLarson) [inline cel/program.go]: This suggests that you can set qualifiers here, which isn't the case.  Either expose the qualifier API, or take the remainder out.

File: cel/program.go [hunk 7]
```diff
@@ -48,6 +48,37 @@ func NoVars() interpreter.Activation {
...
 }
 
+// PartialVars returns a PartialActivation which contains variables and a set of AttributePattern
+// values that indicate variables or parts of variables whose value are not yet known.
+func PartialVars(vars interface{},
+	unknowns ...*interpreter.AttributePattern) (interpreter.PartialActivation, error) {
+	return interpreter.NewPartialActivation(vars, unknowns...)
+}
+
+// AttributePattern represents a top-level variable with an optional set of qualifier patterns.
```
Comment (JimLarson) [inline cel/program.go]: This constructor doesn't allow the optional qualifier patterns.

File: cel/program.go [hunk 8]
```diff
@@ -106,6 +133,13 @@ func newProgram(e *Env, ast *Ast, opts ...ProgramOption) (Program, error) {
 		}
 	}
 
+	// Set the attribute factory after the options have been set.
+	if p.evalOpts&OptPartialEval == OptPartialEval {
```
Comment (JimLarson) [inline cel/program.go:136]: Spaces around "&", please.  Did you run gofmt?

File: interpreter/activation.go [hunk 9]
```diff
@@ -132,19 +131,14 @@ func NewHierarchicalActivation(parent Activation, child Activation) Activation {
...
-	return a
-}
-
-// PartialActivation returns an Activation that will resolve identifier names if present, otherwise
-// will return 'types.Unknown'.
+// NewPartialActivation returns an Activation which contains a list of AttributePattern values
+// representing field and index operations that should result in a 'types.Unknown' result.
 //
-// The input `bindings` may either be of type `Activation` or `map[string]interface{}`.
+// The input `bindings` may either be of type `Activation` or `map[string]interface{}`. The
```
Comment (JimLarson) [inline interpreter/activation.go]: What things can the map values be? (It would be great if you had a single place that names and defines this range of types.)

File: interpreter/attribute_patterns.go [hunk 10]
```diff
@@ -0,0 +1,350 @@
...
+func NewAttributePattern(variable string) *AttributePattern {
+	return &AttributePattern{
+		variable:          variable,
+		qualifierPatterns: []*AttributeQualifierPattern{},
+	}
+}
+
+// Field adds a string qualifier pattern to the AttributePattern. The string may be a valid
+// identifier, or string map key including empty string.
+func (apat *AttributePattern) Field(pattern string) *AttributePattern {
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Consider more consistent naming, e.g. IndexString or QualString.

File: interpreter/attribute_patterns.go [hunk 11]
```diff
@@ -0,0 +1,350 @@
...
+	apat.qualifierPatterns = append(apat.qualifierPatterns,
+		&AttributeQualifierPattern{value: pattern})
+	return apat
+}
+
+// Index adds an int qualifier pattern to the AttributePattern. The index may be either a map or
+// list index.
+func (apat *AttributePattern) Index(pattern int64) *AttributePattern {
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Consider naming IndexInt instead.

File: interpreter/attribute_patterns.go [hunk 12]
```diff
@@ -0,0 +1,350 @@
...
+
+// IndexBool adds a bool qualifier pattern for a map index operation to the AttributePattern.
+func (apat *AttributePattern) IndexBool(pattern bool) *AttributePattern {
+	apat.qualifierPatterns = append(apat.qualifierPatterns,
+		&AttributeQualifierPattern{value: pattern})
+	return apat
+}
+
+// Wildcard adds a special sentinel qualifier pattern that indicates any value will yeild a
+// qualifier match.
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Specify whether the wildcard matches a single level or an arbitrary sequence of levels.

File: interpreter/attribute_patterns.go [hunk 13]
```diff
@@ -0,0 +1,350 @@
...
+func (apat *AttributePattern) Wildcard() *AttributePattern {
+	apat.qualifierPatterns = append(apat.qualifierPatterns,
+		&AttributeQualifierPattern{wildcard: true})
+	return apat
+}
+
+// Matches returns true if the variable matches the AttributePattern variable.
+func (apat *AttributePattern) Matches(variable string) bool {
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Consider "VariableMatches", since it could have qualifiers.  Also specify whether "c" matches "a.b.c" when the namespace is "a.b".

File: interpreter/attribute_patterns.go [hunk 14]
```diff
@@ -0,0 +1,350 @@
...
+
+	"github.com/google/cel-go/common/packages"
+	"github.com/google/cel-go/common/types"
+	"github.com/google/cel-go/common/types/ref"
+)
+
+// AttributePattern represents a top-level variable with an optional set of qualifier patterns.
+//
+// The variable name must always be a string, and may be a qualified name according to the CEL
+// namespacing conventions, e.g. 'ns.app.a'.
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Clarify whether a variable, qualified or not, will go through the namespace/variable resolution.  E.g. if the namespace is "a.b", does an attribute pattern with variable "c" possibly match a.b.c?  Or is it expected to be the fully-qualified name?

File: interpreter/attribute_patterns.go [hunk 15]
```diff
@@ -0,0 +1,350 @@
...
+	return ok && qve.QualifierValueEquals(qpat.value)
+}
+
+// qualifierValueEquator defines an interface for determining if an input value, of valid map key
+// type, is equal to the value held in the Qualifier. This interface is used by the
+// AttributeQualifierPattern to determine pattern matches for non-wildcard qualifier patterns.
+//
+// Note: Attribute values are also Qualifier values; however, Attriutes are resolved before
+// qualification happens. This is an implementation detail, but one relevant to why the Attribute
+// types do no surface in the list of implementations.
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: "do not"

File: interpreter/attribute_patterns.go [hunk 16]
```diff
@@ -0,0 +1,350 @@
...
+	qve, ok := q.(qualifierValueEquator)
+	return ok && qve.QualifierValueEquals(qpat.value)
+}
+
+// qualifierValueEquator defines an interface for determining if an input value, of valid map key
+// type, is equal to the value held in the Qualifier. This interface is used by the
+// AttributeQualifierPattern to determine pattern matches for non-wildcard qualifier patterns.
+//
+// Note: Attribute values are also Qualifier values; however, Attriutes are resolved before
+// qualification happens. This is an implementation detail, but one relevant to why the Attribute
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go:129]: At the code location that ensures that "attributes are resolved before qualification happens", make a reference back to this comment, so that if that guarantee ever changes we'll know to revisit this section.

File: interpreter/attribute_patterns.go [hunk 17]
```diff
@@ -0,0 +1,350 @@
...
+		},
+		adapter:  fac.adapter,
+		provider: fac.provider,
+		fac:      fac,
+	}
+}
+
+// matchesUnknownPatterns returns true if the variable names and qualifiers for a given
+// Attribute value match any of the ActivationPattern objects in the set of unknown activation
+// patterns on the given PartialActivation.
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go:216]: Please give an example here.  I understand the words individually, but I don't understand when they're put all together.

File: interpreter/attribute_patterns.go [hunk 18]
```diff
@@ -0,0 +1,350 @@
...
+func (fac *partialAttributeFactory) matchesUnknownPatterns(
+	vars PartialActivation,
+	attrID int64,
+	variableNames []string,
+	qualifiers []Qualifier) (types.Unknown, error) {
+	patterns := vars.UnknownAttributePatterns()
+	candIndices := map[int]struct{}{}
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Please expand "cand" to "candidate", at least in a comment.

File: interpreter/attribute_patterns.go [hunk 19]
```diff
@@ -0,0 +1,350 @@
...
+type attributeMatcher struct {
+	NamespacedAttribute
+	qualifiers []Qualifier
+	fac        *partialAttributeFactory
+}
+
+// AddQualifier implements the Attribute interface method which adds the Qualifier onto the
+// underlying NamespacedAttribute as well as tracks the Qualifier in internal storage. The
+// double accounting for the Qualifier values is to assist with AttributePattern matching in
+// the TryResolve call.
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Please add an example - I'm not getting the "double accounting".

File: interpreter/attribute_patterns.go [hunk 20]
```diff
@@ -0,0 +1,350 @@
...
+
+// Resolve is an implementation of the Attribute interface method which uses the
+// attributeMatcher TryResolve implementation rather than the embedded NamespacedAttribute
+// Resolve implementation.
+func (m *attributeMatcher) Resolve(vars Activation) (interface{}, error) {
+	obj, found, err := m.TryResolve(vars)
+	if err != nil {
+		return nil, err
+	}
+	if found {
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Consider flipping the test to get the error return indented instead of the "normal" return.

File: interpreter/attribute_patterns.go [hunk 21]
```diff
@@ -0,0 +1,350 @@
...
+			}
+		}
+		if isUnk {
+			return types.Unknown{matchExprID}, nil
+		}
+	}
+	return nil, nil
+}
+
+type attributeMatcher struct {
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go:309]: Add a comment that this will be an Attribute, and why.

File: interpreter/attribute_patterns_test.go [hunk 22]
```diff
@@ -0,0 +1,284 @@
...
+
+type attr struct {
+	maybe bool
+	name  string
+	quals []interface{}
+}
+
+type patternTest struct {
+	pattern *AttributePattern
+	pkg     string
```
Comment (JimLarson) [inline interpreter/attribute_patterns_test.go]: I think we're calling this "container".

File: interpreter/attribute_patterns_test.go [hunk 23]
```diff
@@ -0,0 +1,284 @@
...
+			{name: "ns.var"},
+		},
+	},
+	"var_namespace": {
+		pattern: NewAttributePattern("ns.app.var"),
+		pkg:     "ns.app",
+		matches: []attr{
+			{name: "ns.app.var"},
+			{name: "ns.app.var", quals: []interface{}{int64(0)}},
+			{name: "ns", quals: []interface{}{"app", "var", "foo"}, maybe: true},
```
Comment (JimLarson) [inline interpreter/attribute_patterns_test.go]: [Cel-spec issue 53](https://github.com/google/cel-spec/issues/53) calls for variable `ns` to be disallowed if any `ns.app.*` variable is defined.  This isn't _exactly_ the case here, but if we're working in container `ns.app`, we should probably view a variable `ns` with suspicion, if not disallow it outright.

File: interpreter/attribute_patterns_test.go [hunk 24]
```diff
@@ -0,0 +1,284 @@
...
+		},
+		misses: []attr{
+			{name: "ns.var"},
+			{name: "ns", quals: []interface{}{"var"}, maybe: true},
+		},
+	},
+	"var_field": {
+		pattern: NewAttributePattern("var").Field("field"),
+		matches: []attr{
+			{name: "var"},
```
Comment (JimLarson) [inline interpreter/attribute_patterns_test.go:86]: Make sure that it's clear in the comments in the `cel` package that pattern `a.b` also matches `a` but not `a.c`.

File: interpreter/attributes.go [hunk 25]
```diff
@@ -31,7 +31,7 @@ type AttributeFactory interface {
 	// AbsoluteAttribute creates an attribute that refers to a top-level variable name.
```
Comment (JimLarson) [inline interpreter/attributes.go:31]: Refer to or copy the description of CandidateVariableNames below.

File: interpreter/attributes.go [hunk 26]
```diff
@@ -81,6 +81,26 @@ type Attribute interface {
 	Resolve(Activation) (interface{}, error)
 }
 
+// NamespacedAttribute values are a variable within a namespace, and an optional set of qualifiers
+// such as field, key, or index accesses.
+type NamespacedAttribute interface {
+	Attribute
+
+	// CandidateVariableNames returns the possible namespaced variable names for this Attribute in
+	// the CEL namespace resolution order.
```
Comment (JimLarson) [inline interpreter/attributes.go:97]: The type suggests this can be a sequence of arbitrary strings, but that's not what your'e expecting.  Consider changing this to something that represents only what you want, e.g. `[]string` where it represents just the components of the FQVN, or use type abstraction.

**Review by JimLarson — CHANGES_REQUESTED** [review]

File: interpreter/attribute_patterns_test.go (hunk 23 above)
Comment (TristonianJones) [reply interpreter/attribute_patterns_test.go]: Ah, this is a `MaybeAttribute` which represents an unchecked expression whose checked form might be any one of the following:

1. `id: ns.app.var.foo`
2. `select(id: ns.app.var, field: 'foo')`
3. `select(select(id: ns.app, field: 'var'), field: 'foo')`
4. `select(select(select(id: ns, field: 'app'), field: 'var'), field: 'foo')`

The test ensures that even parsed only attributes will match the pattern correctly.

File: cel/program.go (hunk 8 above)
Comment (TristonianJones) [reply cel/program.go:136]: I think it was the `gofmt` that actually did this. I had spaces and they disappeared.

File: cel/program.go (hunk 6 above)
Comment (TristonianJones) [reply cel/program.go]: `AddQualifierPattern` is a method exposed on the `AttributePattern` directly, so I'm not sure it needs additional publication. I opted to try an give a high-level overview of how to use `AttributePattern`, but I could refer to the `AttributePattern` docs instead.

File: cel/cel_test.go (hunk 3 above)
Comment (TristonianJones) [reply cel/cel_test.go:629]: Some time back, I normalized the whitespace handling in the `AstToString` call so that it now formats the expression to a single line.

File: cel/env.go (hunk 1 above)
Comment (TristonianJones) [reply cel/env.go]: I'll emphasize the latter angle. I don't want to give people the idea that the same input could be evaluated in parallel over multiple threads where CEL somehow shards branch evaluations. That would be cool, but we're not really there.

File: interpreter/attributes.go (hunk 26 above)
Comment (TristonianJones) [reply interpreter/attributes.go:97]: Unfortunately, there is more than one candidate variable name, so this isn't the components of the fully qualified variable name, it's the set of possible FQVN values which could be produced from a parse-only expression.

**Comment by TristonianJones** [comment]
PTAL

File: cel/program.go [hunk 27]
```diff
@@ -50,31 +50,30 @@ func NoVars() interpreter.Activation {
...
+// string field or index qualification `b`. This pattern will match Attributes `a`, and `a.b`,
+// but not `a.c`.
 //
-//   1. ns.myvar["complex-value"]
-//   2. ns.myvar["complex-value"][0]
-//   3. ns.myvar["complex-value"].*.name
+// When using a CEL expression within a container, e.g. a package or namespace, the variable name
+// in the pattern must match the qualified name produced during the variable namespace resolution.
+// For example, when variable `a` is declared within an expression whose container is `ns.app`, the
+// fully qualified variable name may be `ns.app.a`, `ns.a`, or `a` per the CEL namespace resolution
```
Comment (JimLarson) [inline cel/program.go:71]: The term "fully qualified" generally means only the longest expansion, e.g. "fully qualified domain name" means "domains.google.com", not one of the prefixes of that string.

File: interpreter/activation.go [hunk 28]
```diff
@@ -134,20 +134,8 @@ func NewHierarchicalActivation(parent Activation, child Activation) Activation {
...
-// Lazy bindings may be supplied in either of the following forms:
-// - func() interface{}
-// - func() ref.Val
-//
-// The output of the lazy binding will overwrite the variable reference in the internal map.
-//
-// Values which are not represented as ref.Val types on input may be adapted to a ref.Val using
-// the ref.TypeAdapter configured in the environment.
+// The `vars` value may be any value type supported by the interpreter.NewActivation call,
+// but is typically either an existing Activation or map[string]interface{}.
```
Comment (JimLarson) [inline interpreter/activation.go:138]: There doesn't seem to be a `vars` here.

File: interpreter/attribute_patterns.go [hunk 29]
```diff
@@ -24,8 +24,11 @@ import (
 
 // AttributePattern represents a top-level variable with an optional set of qualifier patterns.
 //
-// The variable name must always be a string, and may be a qualified name according to the CEL
-// namespacing conventions, e.g. 'ns.app.a'.
+// When using a CEL expression within a container, e.g. a package or namespace, the variable name
+// in the pattern must match the qualified name produced during the variable namespace resolution.
+// Variable names provided on input to the AttributePattern are taken at face value. For example,
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Consider describing this as the "fully qualified variable name" instead of "taken at face value".

File: interpreter/attribute_patterns_test.go (hunk 23 above)
Comment (JimLarson) [reply interpreter/attribute_patterns_test.go]: So it seems that the container setting isn't really relevant to the test - maybe take it out?  Or make it relevant by dropping the "ns.app" prefix from one of the cases?

But again with Issue 53:  it seems like we're declaring that "ns.app.var" is a real variable.  We might decide that this forbids us from having "ns" or "ns.app" as variables.

At least put in the following comment:
```
// Note that https://github.com/google/cel-spec/issues/53 complains about
// variable names that are a dotted prefix of other qualified variable names,
// so this tests some scenarios which might be disallowed in the future.
```

File: cel/program.go (hunk 27 above)
Comment (TristonianJones) [reply cel/program.go:71]: Whether `a` is declared globally or within `ns.app` is something that the expression itself does not indicate, but rather is determined by the variable declaration. It's possible the fully qualified declaration name for the identifier `a` is `ns.app.a`, `ns.a`, or `a` depending on what the declaration says. Am I missing something in the feedback here?

File: interpreter/attribute_patterns_test.go (hunk 23 above)
Comment (TristonianJones) [reply interpreter/attribute_patterns_test.go]: However, this test is not exercising subsumption, but rather demonstrating that maybe resolution considers the container when attempting to match a parsed-only expression against the attribute pattern. In the examples I typed out earlier, maybe option number 2 is the one that matches.

File: interpreter/attribute_patterns.go (hunk 16 above)
Comment (TristonianJones) [reply interpreter/attribute_patterns.go:129]: Done.

File: cel/cel_test.go (hunk 3 above)
Comment (JimLarson) [reply cel/cel_test.go:629]: My concern is that if we ever make a tweak, we might break not just our tests (bearable), but 3rd-party tests too.  That being said, if you're not trying to be fancy in the formatting, it's probably an acceptable risk. Maybe add a comment in AstToString that it's expected to be stable.

File: cel/program.go (hunk 27 above)
Comment (JimLarson) [reply cel/program.go:71]: Ah, I was misreading the comment - it's saying that `a` might refer to 3 different variables, not that one variable has 3 different "fully-qualified" names.  Have the next sentence start "Pick the _fully_ qualified variable name that makes sense...".

File: interpreter/attribute_patterns.go [hunk 30]
```diff
@@ -0,0 +1,382 @@
...
+}
+
+// Wildcard adds a special sentinel qualifier pattern that will match any single qualifier.
+func (apat *AttributePattern) Wildcard() *AttributePattern {
+	apat.qualifierPatterns = append(apat.qualifierPatterns,
+		&AttributeQualifierPattern{wildcard: true})
+	return apat
+}
+
+// VariableMatches returns true if the variable matches the AttributePattern variable.
```
Comment (JimLarson) [inline interpreter/attribute_patterns.go]: Indicate that the `variable` argument must be fully-qualified.

**Review by JimLarson — CHANGES_REQUESTED** [review]

File: cel/env.go [hunk 31]
```diff
@@ -186,6 +187,65 @@ func (e *Env) TypeProvider() ref.TypeProvider {
...
+// For example, if an expression targets a 'resource' and 'request' attribute and the possible
+// values for the resource are known, a PartialActivation could mark the 'request' as an unknown
+// interpreter.AttributePattern and the resulting ResidualAst would be reduced to only the parts
+// of the expression that reference the 'request'.
+//
+// Note, the expression ids within the residual AST generated through this method have no
+// correlation to the expression ids of the original AST.
+//
+// See the PartialVars helper for how to construct a PartialActivation.
+func (e *Env) ResidualAst(a *Ast, details *EvalDetails) (*Ast, error) {
```
Comment (JimLarson) [inline cel/env.go:232]: What do you think about adding an analogous `ResidualProgram` standalone function?  I'd like to be able to compute a residual of the higher-level graph-of-Programs without peeking inside the Program abstraction.

```
func ResidualProgram(p Program, details *EvalDetails) (Program, error)
```

File: cel/cel_test.go (hunk 3 above)
Comment (TristonianJones) [reply cel/cel_test.go:629]: I'll add a comment to this effect. For fancy formatting, I think they'll be `FormatOptions` passed to the `AstToString()` call

File: cel/env.go (hunk 31 above)
Comment (TristonianJones) [reply cel/env.go:232]: It's worth considering. I'll add a TODO since I think I'd want to generate the residual program a little bit differently than how the `intepreter.PruneAst` is doing it now. Might be a good opportunity to consolidate program generation logic and allow for the creation of an `Ast` from a `Program` rather than just the other way around.

File: cel/program.go (hunk 27 above)
Comment (TristonianJones) [reply cel/program.go:71]: Done.

File: interpreter/attribute_patterns.go (hunk 30 above)
Comment (TristonianJones) [reply interpreter/attribute_patterns.go]: Done.

File: interpreter/attribute_patterns_test.go (hunk 23 above)
Comment (TristonianJones) [reply interpreter/attribute_patterns_test.go]: I've added a comment about how 'maybe' fits into the test. Perhaps I should describe the test-case a bit differently.

**Review by TristonianJones — COMMENTED** [review]
PTAL. I've updated the comments and added TODOs

File: cel/cel_test.go (hunk 3 above)
Comment (JimLarson) [reply cel/cel_test.go:629]: That would be a great solution, keeping the default behavior stable.

**Review by JimLarson — APPROVED** [review]

File: interpreter/attribute_patterns_test.go (hunk 23 above)
Comment (JimLarson) [reply interpreter/attribute_patterns_test.go]: Per our discussion, I see that the matching "ns" plus qualifiers doesn't imply a variable named "ns", since the "unchecked" bit is set, so no warning vs Issue 53 is needed.
